version: '3.8'

services:
  db:
    image: postgres:15
    container_name: loles-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - loles_pgdata:/var/lib/postgresql/data

volumes:
  loles_pgdata:
